version: "3.2"
services:
  wartimer:
    container_name: wartimer
    image: wartimer:latest
    restart: unless-stopped
    environment:
      - DISCORD_CLIENT_TOKEN=<token>
      - DISCORD_CLIENT_ID=<id>
  mongo:
    image: mongo
    restart: always
    volumes:
      - <localpath>:/data/db